### ISSUE TITLE
Change default serializer to JSON from pickle

### ISSUE THREAD

**Issue by kevinlondon** [niwinz/django-redis#161]
The documentation mentions use of `pickle` towards the bottom, but does not include any mentions of the security problems associated with using it. As per the [Python docs](https://docs.python.org/2/library/pickle.html) and [many](https://lincolnloop.com/blog/2013/mar/22/playing-pickle-security/) [blog](http://kevinlondon.com/2015/08/15/dangerous-python-functions-pt2.html) posts, I think we should swap it out for JSON as the default serializer. [Celery](http://celery.readthedocs.org/en/latest/faq.html#isn-t-using-pickle-a-security-concern) famously made a similar switch not too long ago.

If that's too extreme, I think it would be a good idea to add some big warnings about the dangers of using pickle in the docs, and feature a note about the default serialization type right at the top of the docs somewhere.

**Comment by niwinz** [comment]
I undersand, but json has a lot of limitations in terms of data types to store. I think is not going to be changed. if you do not trust your database, just switch to an other serializer.

Thank for the suggestion.

**Comment by tomchristie** [comment]
I'd strongly recommend JSON serialization as a sensible default too, not necessarily in terms of security, but simply because dumping arbitrary python objects to the datastore just isn't a sensible thing to do by default. Using JSON means better visibility, interoperability, and less potential for unexpected side effects on loading data.

Understand that it's not likely to change in this package, but it might be worth bumping the JSONSerializer up in the docs. Personally I think it'd be great to see it front and center in the "2.2. Configure as cache backend" example.
