### ISSUE TITLE
Password url format doc is misleading

### ISSUE THREAD

**Issue by ajeebkp23** [niwinz/django-redis#190]
Hi,

First of all, Thanks for such a nice library.

In this section, https://niwinz.github.io/django-redis/latest/#_configure_as_cache_backend
(Last updated 2016-05-05 20:10:00 EEST )
**This is a examples of url format
redis://[:password]@localhost:6379/0**
IMHO, The above thing is confusing. (I put **[:mypassword]** inplace of **[:password]**). I got error.

Where as in Celery doc, (http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#configuration), it is shown like below.
**redis://:password@hostname:port/db_number**
This worked for me. I think, this representation is more clear.

I think, it is confusing. Kindly update the docs.

**Comment by niwinz** [comment]
Hi @ajeebkp23, thanks for you suggestion, but [something] in multiple representation formats means **something optional**.  Your proposal is also confusing because you are making that like it is mandatory but it isn't. I'm not pretty convinced that the format that celery uses is better I have used in the django-redis doc.

In fact, that examples are directly extracted from redis-py doc so I'm not the only that uses that.

**Comment by ajeebkp23** [comment]
You are right. 

It was my mistake. I wasn't aware of **something optional**. 

Thanks for quick reply.
