### ISSUE TITLE
Documentation update: middleware

### ISSUE THREAD

**Issue by strikaco** [niwinz/django-redis#210]
Thanks for a great plugin. I almost gave up on it entirely though because I couldn't get it working after following the directions. I put the CACHE dictionary in settings.py but nothing ever showed up in my Redis store.

The documentation does not mention that the Django caching middleware needs to be enabled. I figured this much out from [here](http://michal.karzynski.pl/blog/2013/07/14/using-redis-as-django-session-store-and-cache-backend/).

In settings.py, the middleware class list needs to reflect the following, in this order:

```
MIDDLEWARE_CLASSES = [
    'django.middleware.cache.UpdateCacheMiddleware',
    (everything else),
    'django.middleware.cache.FetchFromCacheMiddleware',
]
```

For Django 1.9 I only had to add the last line, but my understanding is that both need to be added in older versions.

**Comment by niwinz** [comment]
Hmm, I'm not clearly understand this issue. As far as I can understand, the middleware just for apply the cache stuff to the entire site and this is completly django stuff, nothing related to django-redis.

I'm not clearly understand why we should document something not directly related to django-redis and is already documented on django?

You are saying that:

> The documentation does not mention that the Django caching middleware needs to be enabled. I figured this much out from here.

But that is not true, the middleware should not be enabled in order to work with django-redis. The middleware is just a more higher level of abstraction that django offers in order to handle cache of the entire site and uses the low-level api that django-redis implements as a compliant django cache backend. So, the middleware are only needed for a specific purpose but they are not mandatory in order to make work django-redis.

**Comment by strikaco** [comment]
Thanks for the response. I think I understand what you're saying.

After following the instructions, I expected django-redis to cache the entire site. Because it did not do this, I assumed it was broken until I enabled the caching middleware. You obviously designed this to do more than just basic caching so I can see why it is not mentioned in the documentation.
