### ISSUE TITLE
4.5.0 PASSWORD change breaks connection setup

### ISSUE THREAD

**Issue by samuelcolvin** [niwinz/django-redis#220]
We've had the following in `settings.py` for the last two years on heroku working fine with django-redis:

``` python
redis_url = urlparse(os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'))
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': '%s:%s:0' % (redis_url.hostname, redis_url.port),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': redis_url.password,
            'CONNECTION_POOL_KWARGS': {'max_connections': 10}
        }
    }
}
```

I just upgraded to 4.5.0 and all redis connections were refused. I've currently reverted back to the previous release, but the docs aren't clear on what settings I should be using.

I think the URI section of the docs is now out of date wrt passwords?

**Comment by samuelcolvin** [comment]
appears to be fixed by correcting `LOCATION` to
```python
CACHES = {
...
        'LOCATION': 'redis://{}:{}/0'.format(redis_url.hostname, redis_url.port),
...
```

but better documentation would still be good.

**Comment by niwinz** [comment]
The old connection string is deprecated in 3.8.x and leaved undocumented. And in 4.5 is now removed, the changelog already says that unused and undocumented very old connection string is now removed. It is nothing related to PASSWORD new option.

If you have improvements to the doc, I gladly merge it ;)

**Comment by hwkns** [comment]
This (and dropping support for Django < 1.8, which was also part of 4.5 changes) is a backwards incompatible change which should require a MAJOR version increment.  Sneaking this into a MINOR version bump is deceptive and irresponsible.

http://semver.org/

**Comment by kevin-brown** [comment]
> ... is a backwards incompatible change ...

Normally I'd agree here, but this was deprecated in a previous major version (3.8). So, one would assume, that by this being deprecated for the better part of 1 major version (3 -> 4) and (at least) 5 minor versions (3.8 -> 4.4), that deprecation would have been handled and corrected.

Also, I don't see any notes anywhere alluding to this package following semver. I've actually found that a good portion of Django-related packages follow the Django versioning style instead of semver.

**Comment by hwkns** [comment]
If only assuming made it so.  It is a backwards incompatible change, there's no debating that.

Fair enough about following Django sytle versioning and not having semver listed anywhere; I made an assumption there that wasn't true.  Django is taking steps toward semver in 2.0, fwiw.

**Comment by bstrdsmkr** [comment]
http://niwinz.github.io/django-redis/latest/#_how_version_number_is_handled

This seems like a pretty strong implication that users should be able to rely on the tenant of point releases not breaking backward compatibility, semver or no.

**Comment by niwinz** [comment]
django-redis does not uses semver, and in fact, the different available branches is for redis server version support. I try to make as less as possible backward incompatible changes, and much of them with large period of time of deprecation... In any case, you should read the changelog upgrade to anything different to a patch version upgrade, that always details all deprecations and all breaking changes.

I'm not using semver just because it does not fits very well for handle different development branches. The django-redis versioning is just A.X.Z (x and z is from semver). The **A** indicates the major branch that is only changed when redis version support is changed, **X** is a major/minor version and **Z** for just bugfixes. 

Semver in my opinion does not has a clear difference between patch and minor, on the end they are pretty the same and is very difficult to decide if I need to change minor o patch.

**Comment by hwkns** [comment]
Semver has no effect whatsoever on having different development branches; it's only relevant to the publicly released versions of the package.  Semver is also quite explicit about the difference between minor and patch:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

A great thing about semver is that you don't have to go read the changelogs for every package every time you want to do a dependency update (our project has about 150 dependencies in `requirements.txt`).  If the major version hasn't changed, it's safe to upgrade.

I realize you aren't likely to change your habits, but I thought I would put the information out there, in case others are reading along and trying to decide how to version their packages.

**Comment by niwinz** [comment]
I'm open to change to semver, but only if it solves the use cases for this package (I'm using semver versioning on other packages that I'm maintaining which not has the same requirements).

As exercise, tell me, which version I should use on 3.x branch when a breaking change need to be done when the 4 is already used for other development branch?

**Comment by hwkns** [comment]
I'm having trouble parsing that question, but I think what you're asking is, if people are already using a `4.x` branch to develop long-term planned breaking changes, and you discover the need for some quick breaking changes (for security reasons, or some other urgent purpose), what version should you use for releasing the quick breaking changes?

In that case, I would probably rename the `4.x` branch to `5.x`, and release the more urgent breaking changes as `4.0.0`.  There are many different ways to handle branching and git workflows, and I think that's the domain your problem lives in; semver is only relevant to the actual released packages.  It might make more sense to have people develop against branches named for specific initiatives or features, rather than numbering them up front and having to re-number them if something comes up.
