### ISSUE TITLE
cache.clear() ignores KEY_PREFIX

### ISSUE THREAD

**Issue by utapyngo** [niwinz/django-redis#245]
The current implementation of clear is:

```python
    def clear(self, client=None):
        """
        Flush all cache keys.
        """

        if client is None:
            client = self.get_client(write=True)

        try:
            count = 0
            for key in client.scan_iter("*"):
                client.delete(key)
                count += 1
            return count
        except _main_exceptions as e:
            raise ConnectionInterrupted(connection=client, parent=e)
```

`client.scan_iter("*")` iterates over all keys regardless KEY_PREFIX. As a result, the whole redis database is cleared and not only the keys starting the configured KEY_PREFIX.

This was fixed before (https://github.com/niwinz/django-redis/issues/168) but has been broken again in https://github.com/niwinz/django-redis/commit/a71d9fbc3a455fcd739e59b884c4c7e99bc21ff5 when fixing https://github.com/niwinz/django-redis/issues/223.

**Comment by niwinz** [comment]
Yes, it ignores it explicitly, as you can read the rationale on the #223

**Comment by utapyngo** [comment]
OK, how can I clear only cache keys that are related to KEY_PREFIX?

**Comment by niwinz** [comment]
Doing manually operation through the raw redis client. What I'm thinking is that it would be good improvement accept an additional parameter on clear method allowing the user only clear the keys with a current KEY_PREFIX. PR is welcome for that!

**Comment by wolever** [comment]
Ug, bumping this one, since it just wiped my production Redis database.

Fortunately nothing of major consequence was lost… but damn, this is super not cool.

I would suggest that:

1. The documentation should be updated to make *very* clear that a separate database should be used just for caching, and

2. A warning should be issued if `KEY_PREFIX` is non-blank and not explicitly suppressed; after all, as long as it's not safe for `django-redis` to share a database with other data, there's no reason it would need a key prefix.

I'm happy to provide a PR for both of these.

**Comment by niwinz** [comment]
The PR will be welcome!
