### ISSUE TITLE
Unable to call cache.keys() after upgrade

### ISSUE THREAD

**Issue by beittenc** [niwinz/django-redis#251]
I've got an application that's been running Django 1.5 and django-redis 3.7.2 successfully for a long time now, but obviously I need to upgrade the versions. I've updated to Django 1.11 and django-redis 4.7.0 and everything is working fine except calls to cache.keys(). For whatever reason, that method isn't exposed and my application relies on it for some critical functionality.

Here's the relevant portion of my settings.py:

```python
CACHE_LOCATION = 'redis://%s:%s/%s' % (env['REDIS_HOST'], env['REDIS_PORT'], 1)

CACHES = {
    "default": {
        "BACKEND": 'django_redis.cache.RedisCache',
        "LOCATION": CACHE_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
       },
    }
}
```

Everything is being stored in Redis just fine. If I check the __class__ of the cache I'm getting from Django, it's coming back as django.core.cache.DefaultCacheProxy instead of django_redis.cache.RedisCache. The proxy class doesn't have either keys() or iter_keys() in the function list and calling them throws an error.

I've tried every version of Django from 1.8 through 1.11 as well as both 4.7.0 and 3.8.4 of django-redis with no luck. I found something similar in #167, but there was no resolution (and my problem isn't exactly the same).

I'm open to any and all suggestions on how to resolve this. Losing the keys() functionality is going to be a problem and I need to get this update done soon.

**Comment by niwinz** [comment]
In recent versions of django, the default access to the default cache backend is a proxy object that is limited to the django cache api interface. As django allows to have multiple caches, there are an other way to access to the cache, that does not creates the proxy. Let see an example:

```python
>>> from django.core.cache import cache, caches
>>> cache
<django.core.cache.DefaultCacheProxy object at 0x7fd4171a4860>
>>> caches["default"]
<django_redis.cache.RedisCache object at 0x7fd4144f07b8>
```

The `cache` object is a proxy, but `caches` is a dictionary-like object that allows you access directly to the cache backend (without a proxy). That is the way you need to use in order to have the access to the `keys` and `iter_keys` methods.

**Comment by beittenc** [comment]
Could you update the documentation to reflect that? The documentation currently says that cache.keys() will work with no indication that this isn't true on all versions of Django.

**Comment by niwinz** [comment]
Yes, I'll do it ;)
