### ISSUE TITLE
'redis' is deprecated; please use 'redispy'

### ISSUE THREAD

**Issue by joovel** [niwinz/django-redis#259]
The pypi `redis` module stopped at 2.10.5 and new releases are not being provided. A newer module, `redispy`, forked 2.10.5 plus later changes, and was released on pypi. The newer module includes support for the geo commands released in Redis 3.2.

Can you change your requirements to bring in `redispy` instead of `redis`?

**Comment by edmorley** [comment]
The existing `redis` module ([pypi](https://pypi.python.org/pypi/redis)) has since seen much more activity:
https://github.com/andymccurdy/redis-py/commits/master


...and the only fix on the fork ([pypi](https://pypi.python.org/pypi/redispy)) not on the original is:
https://github.com/JamieCressey/redispy/commit/2cc9bafad8f0c851ab012635f09ae9b591fb1575

I would re-ping the original package to (a) ask them to release a new version on pypi, (b) merge those outstanding PRs for that issue.

**Comment by niwinz** [comment]
On the end I don't have solid decision on this. So I keep this open until we'll have more better info.

**Comment by niwinz** [comment]
Thanks for the info. Seems like keep the original dep is the way to go.
