### ISSUE TITLE
django-redis==3.8.4 fails with django 1.11

### ISSUE THREAD

**Issue by scottwoodall** [niwinz/django-redis#316]
django-redis==3.8.4 is using `get_cache` [1] which was removed in django 1.9 [2]

This throws the following exception:

```
InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name get_cache
```

[1] https://github.com/niwinz/django-redis/blob/3.8.x/django_redis/__init__.py#L3
[2] https://docs.djangoproject.com/en/2.0/releases/1.9/#features-removed-in-1-9

**Comment by kevin-brown** [comment]
[3.8.4 was released in April 2015.](https://github.com/niwinz/django-redis/blob/8616a4df33125772e4252ec39121c2e17bc12a05/setup.py) ([PyPI verification](https://pypi.python.org/pypi/django-redis/3.8.4))

I would highly recommend trying to upgrade to the 4.x line of django-redis, which appears to support Django 1.11 ([since at least 4.8.0](https://github.com/niwinz/django-redis/commit/2ac2a6c25f81a2ceca78bcc602992cf50bd551bb), likely earlier).

**Comment by scottwoodall** [comment]
@kevin-brown Does 3.8.4 support Django 1.11 or am I misunderstanding the docs?

**Comment by kevin-brown** [comment]
The docs appear to have gone out of sync in https://github.com/niwinz/django-redis/commit/299ece378262e00762dafa66b8daae0fbe247fe5, likely because nobody realized that 3.8.x is still in use by a few of us (myself included, old project). That puts it at a few months ago.

The best course of action of this project is probably to remove references to the 3.8.x line from the documentation and just let it go. It hasn't been updated since 2015 and it's become clear that it's not actually supported anymore.
