### ISSUE TITLE
Sentinel support in django-redis

### ISSUE THREAD

**Issue by matusvalo** [niwinz/django-redis#328]
Currently there is no support for sentinel in django-redis. There are several implementation e.g. [1] but they are not working with current version of django-redis. django-redis has multiple closed issues for sentinel support: #186, #87, Is it feasible to add new sentinel client to django-redis itself? Default client is already supporting Master-Slave configuration, hence adding sentinel support should not be big development effort. I am willing to fix [1] and create PR to django-redis. Is welkome such contribution to django-redis?

[1] https://github.com/SpatialBuzz/django-redis-sentinel

**Comment by camflan** [comment]
I'm also interested in this

**Comment by niwinz** [comment]
django-redis has pluggable clients and everybody can build a client that supports sentinel and use it. I'm not including sentinel in core because i'm not using it. And i can't dedicate time to maintain it...
I don't know how it works and i cant maintain a client without good knowledge of sentinel and its corner cases. 

If there are interest in this, just fork [1] repository and update it and send back the PR (or request the repository transfer if the original maintainer is not longer maintaining it). The changes should be pretty small. I think someone who known's and uses sentinel can do better job than me developing and maintaining the sentinel client.
